name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            openjdk-17-jdk \
            zip unzip \
            wget \
            libncurses5 \
            libstdc++6 \
            libffi-dev \
            libssl-dev

      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip
          mv cmdline-tools cmdline-tools/latest
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --licenses

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Build APK
         working-directory: android_app
         run: |
         yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android_app/bin/*.apk
