name: Build APK

on:
  push:
    paths:
      - 'android_app/**'
      - '.github/workflows/build-apk.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install build tools
        run: |
          pip install buildozer cython kivy requests pyjnius
      
      - name: Create .buildozer directory
        run: mkdir -p ~/.buildozer
      
      - name: Build APK
        working-directory: android_app
        run: |
          buildozer android release
        env:
          P4A_RELEASE_ALIAS: android
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: docuvoice-apk
          path: android_app/bin/*.apk
          retention-days: 30
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: android_app/bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
